# Acknowledgement

https://github.com/zekelabs/data-science-complete-tutorial



# 1. Introduction to Numpy
Numpy is a Library in python that specializes in dealing with multidimensional Arrays. The cool features of Numpy are
* **Automatic Checking :** Numpy ndArrays automatically check the consistancy of data. For instance, it is not possible to have 1st row with 2 elements and 2nd row with 3 elements
* **Contiguous Storage :** Unlike Python Lists, Numpy stores the data in contiguous Memory Locations, leading to lesser Space
* **Faster Vector Arithmatics :** Because of contiguous storage, the operations are performed faster as compared to default Python Execution for Lists

In [1]:
# Importing Numpy
import numpy as np

## 1.1 Initialization of 1D array in Python
A numpy array comes with 2 important state variables. Just like Python, it automatically detects dtype (if not mentioned)
* dtype
* shape

#### 1.1.1 Initialization from python List
numpy.array( list **)**


In [2]:
# Initializing from Python List
v = np.array([1,4,9,3,2, 2020.617])
print ('1D array in numpy is %s\n'%v)
print ('dtype of the numpy array is %s\n'%str(v.dtype))
print ('shape of the numpy array is %s\n'%v.shape)

1D array in numpy is [1.000000e+00 4.000000e+00 9.000000e+00 3.000000e+00 2.000000e+00
 2.020617e+03]

dtype of the numpy array is float64

shape of the numpy array is 6



#### 1.1.2 Initialization via arange
numpy.arange(**\[**start, **\]**stop, **\[**step, **\]** dtype=None)

In [3]:
v1 = np.arange(3)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,4)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-8,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)



Creating a numpy array via arange (stop=5) : [0 1 2]

Creating a numpy array via arange (start=2,stop=5) : [2 3]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6]



## 1.2. Initialization of 2D array in Python
When we talk about 2D array, it is important to note that Numpy stores Matrix is ***Row Major Format***. Row major format means that the the complete row will be stored first and then the next row will be stored and so on. You can choose to store a matrix in colum major format by mentioning ***order='F'*** on ndarray creation, which means ***Column Major Format***  or *Fortran Style Format*. 


#### 1.2.1 Initialization from List of List
numpy.array **(** ***object***, dtype=None **)**

Here the matrix that we have taken is 
$$mat = \begin{bmatrix}1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

#### 1.2.2 Initialization with zero/ones
numpy.**zeros**(*shape*, dtype=float)  
numpy.**ones**(*shape*, dtype=float)

In [4]:
mat_zeros = np.zeros(shape=(3,2))
print ('Zeros Matris of shape %s is \n%s\n'%(mat_zeros.shape,mat_zeros))
mat_ones = np.ones(shape=(2,3))
print ('Ones Matris of shape %s is \n%s\n'%(mat_ones.shape,mat_ones))


Zeros Matris of shape (3, 2) is 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Matris of shape (2, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]]



#### 1.2.3 Initialization with Random Values
**1.2.3.1** numpy.**random.random**(*size=None*,)  
**1.2.3.2** numpy.**random.randint**(low, high, *size=None*, dtype='I') : The value of matrix lies between low and high-1  
**1.2.3.3** numpy.**random.randn**($d_0,d_1,\cdots,d_n$)


In [5]:
#Using numpy.random.random
mat1 = np.random.random(size=(3,3))
print ('matrix generated from numpy.random.random is \n%s\n'%mat1)
mat2 = np.random.randint(low=0,high=2,size=(2,2))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)
mat3 = np.random.randn(2,4)
print ('matrix generated from numpy.random.randn is \n%s\n'%mat3)


matrix generated from numpy.random.random is 
[[0.86706692 0.05866723 0.62908751]
 [0.0111641  0.31769988 0.99942093]
 [0.56266573 0.21378056 0.72896348]]

matrix generated from numpy.random.random is 
[[0 1]
 [0 0]]

matrix generated from numpy.random.randn is 
[[ 1.75200681  0.81072897  1.50192714 -0.29839098]
 [ 0.11218574 -0.11766625 -1.66325347  0.16436925]]



## 1.3. Slicing and Indexing in Numpy
Just like python, numpy also has 0 indexing. Let us see some of the commonly used slicing techniques .  
* Generic Slicing Operation : \[start\]:\[end\]:\[jump\]
* Only jump    **::2**
* Only end    **:5**
* Start and jump **2::-1**
* End and Jump **:5:2**
* Start, end and jump **2:7:3**


#### 1.3.1 Remove n elements
vec\[:*-n*\]

In [6]:
pymat = [[1,2,3,7],[4,5,6,8]]
npmat = np.array(pymat)
print ('numpy matrix is \n%s\n'%npmat)
print ('Flattened version of numpy matrix is %s\n'%npmat.flatten())
# By flatten the matrix becomes row major 1D vector (This is the way in which a matrix is stored in memory). 


numpy matrix is 
[[1 2 3 7]
 [4 5 6 8]]

Flattened version of numpy matrix is [1 2 3 7 4 5 6 8]



In [7]:
vec = np.arange(17)
vec1 = vec[:-5]
print ('Result of removing last 3 elements from range(10) : \n%s\n'%vec1)

Result of removing last 3 elements from range(10) : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]



#### 1.3.2 Access elements at even indices in a 1D array
vec[::2]

In [8]:

vec1 = np.arange(0,30,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::2]
print ('Elements at even indices are %s\n'%vec2)


Original array is [ 0  3  6  9 12 15 18 21 24 27]

Elements at even indices are [ 0  6 12 18 24]



#### 1.3.3 Access elements at indices in reverse order
vec[::-1]

In [9]:
vec1 = np.arange(0,10,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[::-1]
print ('Elements for indices in reverse is %s\n'%vec2)

Original array is [0 3 6 9]

Elements for indices in reverse is [9 6 3 0]



#### 1.3.4 Access elements present for a range of indices
vec[a:b]

In [10]:
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[2:5]
print ('Elements for indices 2:5 is %s\n'%vec2)

Original array is [ 0  3  6  9 12 15 18]

Elements for indices 2:5 is [ 6  9 12]



#### 1.3.5 Access a particular set of index given by a list
vec[idxlist]

In [11]:
idx=[0,1,5]
vec1 = np.arange(0,20,3)
print ('Original array is %s\n'%vec1)
vec2 = vec1[idx]
print ('Subarray constructed by indices %s is %s\n'%(idx,vec2))

Original array is [ 0  3  6  9 12 15 18]

Subarray constructed by indices [0, 1, 5] is [ 0  3 15]



#### 1.3.6 Creating a submatrix

In [12]:
mat = np.random.randint(0,6,(3,3))
# Create a submatrix with first 2 rows and last 2 columns
submat1 = mat[0:2,-2:]
print ('Original Matrix is \n%s\n'%mat)
print ('Sub Matrix with first 2 rows and last 2 columns is \n%s\n'%submat1)
submat2 = mat[:,3:0:-1]
print ('After flipping the columns of the matrix, it looks : \n%s\n'%submat2)

Original Matrix is 
[[2 1 2]
 [5 3 0]
 [5 2 3]]

Sub Matrix with first 2 rows and last 2 columns is 
[[1 2]
 [3 0]]

After flipping the columns of the matrix, it looks : 
[[2 1]
 [0 3]
 [3 2]]



#### 1.3.7 Horizontal Matrix splitting
numpy.**hsplit**(ary, *indices_or_sections*)  
  
hsplit basically splits a matrix across the horizontal plane based on the indices. Do note that the ***number of rows*** always remains ***constant*** in each section after the horizontal splitting.

![](img/1.3.7-hsplit-01.jpg)

In [13]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2,sp3 = np.hsplit(mat,[4,6])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))
print ('Third split of shape %s, is \n%s\n'%(sp3.shape,sp3))

Original matrix of shape (3, 7), is 
[[0 4 4 3 3 1 1]
 [2 5 3 4 4 2 4]
 [0 5 2 1 5 2 3]]

First split of shape (3, 4), is 
[[0 4 4 3]
 [2 5 3 4]
 [0 5 2 1]]

Second split of shape (3, 2), is 
[[3 1]
 [4 2]
 [5 2]]

Third split of shape (3, 1), is 
[[1]
 [4]
 [3]]



#### 1.3.8 Vertical Matrix Splitting
numpy.**vsplit**(ary, *indices_or_sections*)  
  
vsplit is yet another operation which splits the matrix across the vertical plane based on the ***'rowwise split-index array'***. The ***number of columns*** always remain ***constant*** in each split.

In [14]:
mat = np.random.randint(0,6,(3,7))
sp1,sp2 = np.vsplit(mat,[1])
print ('Original matrix of shape %s, is \n%s\n'%(mat.shape,mat))
print ('First split of shape %s, is \n%s\n'%(sp1.shape,sp1))
print ('Second split of shape %s, is \n%s\n'%(sp2.shape,sp2))

Original matrix of shape (3, 7), is 
[[1 0 3 5 3 3 3]
 [4 0 2 5 0 0 3]
 [2 0 4 2 4 4 2]]

First split of shape (1, 7), is 
[[1 0 3 5 3 3 3]]

Second split of shape (2, 7), is 
[[4 0 2 5 0 0 3]
 [2 0 4 2 4 4 2]]



> ### *Class Examples for 1.1 to 1.3*
>
> 1. Create a matrix of size (2,3) with random binary values
> 2. Find the sum of all 2x2 blocks (overlapping) for a random integer matrix of size (3,5) 

## 1.4. Understanding - Pass By Reference 
Just like python lists, Numpy also exhibits default pass-by-reference behavior


In [15]:
mat1 = np.random.random((2,3))
pt1 = mat1[0].__array_interface__['data'][0]
print ('Memory Location of mat1[0] is : %s\n'%pt1)
pt2 = mat1[1].__array_interface__['data'][0]
print ('Memory Location of mat1[1] is : %s\n'%pt2)
print ('Difference in Memory Location for 3 elements  is : %s bytes\n'%(pt2-pt1))
print ('Memory jump = 8 bytes')


Memory Location of mat1[0] is : 4441042320

Memory Location of mat1[1] is : 4441042344

Difference in Memory Location for 3 elements  is : 24 bytes

Memory jump = 8 bytes


#### 1.4.1 Experiment : Change the value of array by Reference

In [16]:
def identity(elem):
    return elem
v = np.array([1,2,3])
v1 = v # Copy by reference
v1[0]=10
print ('Value of v, after v1 is modified is %s\n'%v)
# Pass by Function 
v = np.array([1,2,3])
v1 = identity(v) # Copy by reference
v1[0]=10
print ('Value of v after func(v) is modified is %s\n'%v)
v = np.array([1,2,3])
v1 = v.copy() # Copy by reference
v1[0]=10
print ('Value of v after v.copy() is modified is %s\n'%v)

Value of v, after v1 is modified is [10  2  3]

Value of v after func(v) is modified is [10  2  3]

Value of v after v.copy() is modified is [1 2 3]



#### 1.4.2 Experiment : Change the value of matrices by Reference

In [17]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print ('Original Matrix is \n%s\n'%mat)

#1 Add 10 to all the even indexes in matrix
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1 = mat[::2,::2]
mat1+=10
print (' Matrix with 10 added to even indices is \n%s\n'%mat1)
# Changes in mat1 are reflected in mat. This happens because the default assignment in numpy is 'pass by reference'

Original Matrix is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix with 10 added to even indices is 
[[11 13]
 [17 19]]



> **Note :** mat1+=10 is different from mat1=mat1+10, as a new space is allocated for mat1 in the latter case.

## 1.5 Broadcast Operation in Numpy
Broadcast Operation is like a razor-sharp knife, to be used with great care. It is a way to ***broadcast*** data of lower or same  dimension onto another ndarray. It is similar to ***map*** operation in python, scala, hadoop.  Broadcast rules are not limited to 2D array. There are extremely specific set of rules for nd-array broadcasting. You can visit ***[numpy documentation on broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)*** to get the complete picture. However, we will be restricting the discussion to only 2D-matrices.



In [18]:
mat = np.random.randint(0,6,(3,5))
print ('mat is \n%s\n'%mat)
v = np.array([10,20,30,40,50])
print ('v is \n%s\n'%v)
print ('mat+1 is \n%s\n'%(mat+1)) # Similar behaviour in case of np.array([1])
print ('mat+v is \n%s\n'%(mat+v))
print ('mat*v is \n%s\n'%(mat*v))
print ('mat+mat is \n%s\n'%(mat+mat))
print ('mat*mat is \n%s\n'%(mat*mat))


mat is 
[[5 5 1 5 2]
 [0 4 3 1 0]
 [4 0 2 1 3]]

v is 
[10 20 30 40 50]

mat+1 is 
[[6 6 2 6 3]
 [1 5 4 2 1]
 [5 1 3 2 4]]

mat+v is 
[[15 25 31 45 52]
 [10 24 33 41 50]
 [14 20 32 41 53]]

mat*v is 
[[ 50 100  30 200 100]
 [  0  80  90  40   0]
 [ 40   0  60  40 150]]

mat+mat is 
[[10 10  2 10  4]
 [ 0  8  6  2  0]
 [ 8  0  4  2  6]]

mat*mat is 
[[25 25  1 25  4]
 [ 0 16  9  1  0]
 [16  0  4  1  9]]



## 1.6 Matrix Operations 
There are two major matix Operations which are important for us.
1. Inner Product
  * Vector Vector
  * Matrix Vector 
  * Matrix Matrix
2. Outer product

#### 1.6.1 Inner Product
In terms of Inner Product or Dot product, <v,w> will be be nothing but sum of element wise product.
$$<v,w> = \sum v_i*w_i = \begin{bmatrix} v_0 & v_1 & \cdots & v_n \end{bmatrix}\begin{bmatrix} w_0 \\ w_1 \\ \cdots \\ w_n \end{bmatrix}$$
So, the dot product between vector $v=[1,2,3]$ and  $w=[2,4,6]$ will be 
$$\begin{align}1*2 + 2*4 + 3*6 \\ 2+8+18 \\ 28\end{align}$$  
We will be covering matrix matrix multiplication in much depth in next-to-next chapter, but you can take it for granted as of now.
#### 1.6.2 Outer Product
The **outer product** on other end is 
$$\begin{bmatrix} v_0 \\ v_1 \\ \cdots \\ v_n \end{bmatrix}\begin{bmatrix} w_0 & w_1 & \cdots & w_n \end{bmatrix} = \begin{bmatrix}v_0w_0 & \cdots & v_0w_j & \cdots & v_0w_n \\ \vdots && \vdots && \vdots \\ v_iw_0 & \cdots & v_iw_j & \cdots & v_iw_n \\ \vdots && \vdots && \vdots \\ v_nw_0 & \cdots & v_nw_j & \cdots & v_nw_n    \end{bmatrix} $$

In [19]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])
vec2 = np.array([2,4,6])
print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector dot product is <v1,v2> is %s\n'%np.dot(vec1,vec2))
print ('---------------\n')

print ('Matrix is\n%s\n'%mat)
print ('Vector v2 is\n%s\n'%vec1)

print ('Matrix Vector product is <mat,vec1> is \n%s\n'%np.dot(mat,vec1))
print ('Matrix Matrix multiplication is <mat,mat> is \n%s\n'%np.dot(mat,mat))
print ('---------------\n')

print ('Vector v1 is %s\n'%vec1)
print ('Vector v2 is %s\n'%vec2)
print ('Vector Vector outer product is <v1,v2> is \n%s\n'%np.outer(vec1,vec2))


Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector dot product is <v1,v2> is 28

---------------

Matrix is
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Vector v2 is
[1 2 3]

Matrix Vector product is <mat,vec1> is 
[ 8 26 44]

Matrix Matrix multiplication is <mat,mat> is 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]

---------------

Vector v1 is [1 2 3]

Vector v2 is [2 4 6]

Vector Vector outer product is <v1,v2> is 
[[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]



## 1.7 Statistical Functions
1. **np.mean**(data,axis=0)
2. **np.var**(data,axis=0)
3. **np.sum**(data,axis=0)
4. **np.max**(data,axis=0)
5. **np.min**(data,axis=0)
6. **np.percentile**(data, percentage,axis=0)

In [20]:

mat = np.arange(9).reshape((3,3))
print ('Original matrix is \n%s\n'%mat)
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0))
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))
print ('---------------------------\n')
print ('Overall varience of matrix is %s\n'%np.var(mat))
print ('Overall sum of matrix is %s\n'%np.sum(mat))
print ('Overall min of matrix is %s\n'%np.min(mat))
print ('Overall max of matrix is %s\n'%np.max(mat))

print ('-------------------------------------\n')
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))


Original matrix is 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Overall mean of matrix is 
4.0

Row mean of matrix is 
[3. 4. 5.]

Column mean of matrix is 
[1. 4. 7.]

---------------------------

Overall varience of matrix is 6.666666666666667

Overall sum of matrix is 36

Overall min of matrix is 0

Overall max of matrix is 8

-------------------------------------

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



## 1.8 Miscellenous Functions
In this section, we will be discussing some important miscellenous Functions which come in handy for matrix manipulation.
#### 1.8.1 squeeze
numpy.**squeeze**(a,axis=None)  
This function tries to reduce the excess dimensions which have only 1 element. If we print the shape of the ndary, these excess dimension will have a 1 in that particular dimension's index. For example, a nd-matrix with shape (1,2,3,1), has $0^{th}$ and $3^{rd}$ dimension as excess.

In [21]:
ndmat = np.zeros(shape=(1,2,3,3,1))
print ('Original Shape of ndmat is %s\n'%str(ndmat.shape))
ndmat1 = np.squeeze(ndmat)
print ('Shape of np.squeeze(ndmat) is %s\n'%str(ndmat1.shape))



Original Shape of ndmat is (1, 2, 3, 3, 1)

Shape of np.squeeze(ndmat) is (2, 3, 3)



#### 1.8.2 transpose
numpy.**transpose**(a, *axes=None*)  
This function reverses the axes for 2D array.  
For multidimensional array, it permutes the matrix according to the axis argument

In [22]:
mat = np.zeros(shape=(2,3))
print ('Original Shape of 2D matrix is %s\n'%str(mat.shape))
mat_transpose = np.transpose(mat)
print ('Shape of np.transpose(mat) is %s\n'%str(mat_transpose.shape))
mat_transpose[1,0] = 1
print ('np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix\n')
print ('---------------------------------\n')
# NDimensional matrix
ndmat = np.zeros(shape=(2,3,4))
print ('Original Shape of nDimensional matrix is %s\n'%str(ndmat.shape))
ndmat_transpose = np.transpose(ndmat)
print ('Shape of np.transpose(ndmat) is %s\n'%str(ndmat_transpose.shape))
ndmat_special_transpose = np.transpose(ndmat, axes = [0,2,1])
print ('Shape of np.transpose(ndmat, axes=[0,2,1]) is %s\n'%str(ndmat_special_transpose.shape))


Original Shape of 2D matrix is (2, 3)

Shape of np.transpose(mat) is (3, 2)

np.transpose is by yet again assignment by reference, as changes in transpose reflects in the original matrix

---------------------------------

Original Shape of nDimensional matrix is (2, 3, 4)

Shape of np.transpose(ndmat) is (4, 3, 2)

Shape of np.transpose(ndmat, axes=[0,2,1]) is (2, 4, 3)



# Chapter 1 Assignment
1. Create a null array of size 10 but the fifth value which is 1
2. Reverse a above created array (first element becomes last)
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 3x3x3 array with random values
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Create a 2d array with 1 on the border and 0 inside
9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
10. Extract the integer part of a random array
11. Create a 5x5 matrix with row values ranging from 0 to 4
12. Create a random vector of size 10 and sort it
13. Consider two random array A anb B, check if they are equal
14. How to tell if a given 2D array has null columns?
15. Considering a four dimensions array, how to get sum over the last two axis at once?
16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

# Chapter 1 Answers

In [23]:
# Question 1
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
# Question 2
reversed_arr = arr[::-1]
print(reversed_arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [37]:
# Question 3
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Question 4
Find indices of non-zero elements from [1,2,0,0,4,0]

In [41]:
# Question 4
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices[0])

[0 1 4]


# Question 5
Create a 3x3x3 array with random values

In [42]:
# Question 5
arr_3d = np.random.random((3, 3, 3))
print(arr_3d)

[[[0.81937494 0.20610877 0.72232307]
  [0.93552766 0.14574664 0.51236709]
  [0.20837215 0.84013534 0.15575637]]

 [[0.14463192 0.77939318 0.89963562]
  [0.63414926 0.66184295 0.61394813]
  [0.25103033 0.30280247 0.47303542]]

 [[0.55950707 0.68692977 0.83788131]
  [0.0222786  0.94651853 0.81698054]
  [0.18729509 0.43819695 0.29332235]]]


# Question 6
Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
# Question 6
arr_10x10 = np.random.random((10, 10))
print(np.min(arr_10x10))
print(np.max(arr_10x10))

Minimum value: 0.012610106978376723
Maximum value: 0.964868594584966


# Question 7
Create a random vector of size 30 and find the mean value

In [32]:
# Question 7
vector_30 = np.random.random(30)
print(np.mean(vector_30))

Mean value of random vector of size 30: 0.5168449555861071


# Question 8
Create a 2d array with 1 on the border and 0 inside

In [33]:
# Question 8
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Question 9
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [71]:
# Question 9
A = np.array([[1, 5, 3], [2, 8, 5], [3, 5, 7], [5, 4, 9], [3, 4, 5]])
B = np.array([[1, 2], [3, 4], [5, 6]])
nine = np.dot(A, B)
print(A)
print(B)
print (nine)

[[1 5 3]
 [2 8 5]
 [3 5 7]
 [5 4 9]
 [3 4 5]]
[[1 2]
 [3 4]
 [5 6]]
[[31 40]
 [51 66]
 [53 68]
 [62 80]
 [40 52]]


# Question 10
Extract the integer part of a random array

In [64]:
# Question 10
random_array = np.random.random((3, 3)) * 10
integer_part = random_array.astype(int)
print(integer_part)

[[4 1 7]
 [4 8 3]
 [3 9 0]]


# Question 11
Create a 5x5 matrix with row values ranging from 0 to 4

In [62]:
# Question 11
row_values = np.arange(5)
matrix_5x5 = np.tile(row_values, (5, 1))
print(matrix_5x5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# Question 12
Create a random vector of size 10 and sort it

In [29]:
# Question 12
vector_10 = np.random.random(10)
sorted_vector = np.sort(vector_10)
print(sorted_vector)

Original vector: [0.01043262 0.65079888 0.39024992 0.20286162 0.3094237  0.67861551
 0.48735782 0.55244982 0.98947128 0.28966271]
Sorted vector: [0.01043262 0.20286162 0.28966271 0.3094237  0.39024992 0.48735782
 0.55244982 0.65079888 0.67861551 0.98947128]


# Question 13
Consider two random array A and B, check if they are equal

In [28]:
# Question 13
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(np.array_equal(A, B))

Array A: [1 2 3]
Array B: [1 2 3]
Array C: [1 2 4]
A equals B: True
A equals C: False


# Question 14
How to tell if a given 2D array has null columns?

In [45]:
# Question 14
matrix_with_null_column = np.array([[1, 0, 3],
                                    [4, 0, 6],
                                    [7, 0, 9]])

null_columns = np.where(np.all(matrix_with_null_column == 0, axis=0))[0]
print(null_columns)
print(len(null_columns) > 0)

[1]
True


# Question 15
Considering a four dimensions array, how to get sum over the last two axis at once?

In [61]:
# Question 15
A = np.random.randint(0, 10, (2, 3, 4, 5))

fifteen = A.sum(axis=3).sum(axis=2)
print(fifteen)

[[87 99 95]
 [96 83 95]]


# Question 16
Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [51]:
# Question 16
A = np.random.random((5, 5, 3))
B = np.random.random((5, 5))

result = A * B[:, :, np.newaxis]
print(result.shape)

(5, 5, 3)


# Question 17
Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [58]:
# Question 17
A = np.random.randint(0, 10, size=(10,10))

print("Original 10x10 matrix:")
print(A)

print("All contiguous 3x3 submatrices:")
for i in range(8):
    for j in range(8):
        print(f"Submatrix at position ({i}, {j}):")
        print(A[i:i+3, j:j+3])

Original 10x10 matrix:
[[7 7 7 9 0 0 3 0 3 1]
 [2 3 0 8 9 3 6 9 2 3]
 [4 7 0 2 8 1 2 1 2 1]
 [0 7 4 7 2 7 7 7 4 1]
 [1 3 8 0 5 5 5 6 7 2]
 [9 7 9 7 5 0 3 5 1 0]
 [4 9 9 9 5 4 8 2 4 4]
 [8 4 6 7 9 3 6 0 7 6]
 [7 4 8 7 6 3 8 7 6 8]
 [9 6 6 8 7 4 8 8 4 6]]
All contiguous 3x3 submatrices:
Submatrix at position (0, 0):
[[7 7 7]
 [2 3 0]
 [4 7 0]]
Submatrix at position (0, 1):
[[7 7 9]
 [3 0 8]
 [7 0 2]]
Submatrix at position (0, 2):
[[7 9 0]
 [0 8 9]
 [0 2 8]]
Submatrix at position (0, 3):
[[9 0 0]
 [8 9 3]
 [2 8 1]]
Submatrix at position (0, 4):
[[0 0 3]
 [9 3 6]
 [8 1 2]]
Submatrix at position (0, 5):
[[0 3 0]
 [3 6 9]
 [1 2 1]]
Submatrix at position (0, 6):
[[3 0 3]
 [6 9 2]
 [2 1 2]]
Submatrix at position (0, 7):
[[0 3 1]
 [9 2 3]
 [1 2 1]]
Submatrix at position (1, 0):
[[2 3 0]
 [4 7 0]
 [0 7 4]]
Submatrix at position (1, 1):
[[3 0 8]
 [7 0 2]
 [7 4 7]]
Submatrix at position (1, 2):
[[0 8 9]
 [0 2 8]
 [4 7 2]]
Submatrix at position (1, 3):
[[8 9 3]
 [2 8 1]
 [7 2 7]]
Submatrix at posit

# Question 18
Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [57]:
# Question 18
A = np.arange(16 * 16).reshape(16, 16)
print("Original 16x16 array: ")
print(A)

block_sums = []
for i in range (0, 16, 4):
    for j in range(0, 16, 4):
        block = A[i:i+4, j:j+4]
        block_sum = np.sum(block)
        block_sums.append(block_sum)
block_sums_array = np.array(block_sums).reshape(4, 4)
print("Block sums (4x4): ")
print(block_sums_array)

Original 16x16 array: 
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
 [ 16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63]
 [ 64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95]
 [ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175]
 [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223]
 [224 225 226 227 228 229 230 231 232 2

# Prompts used

## Question 1

**Task:** Create a null array of size 10, but make the fifth value `1`.

```text
Write Python NumPy code to create an array of size 10 filled with zeros. Then set the fifth element to 1 and print the final array.
```

---

## Question 2

**Task:** Reverse the array created above.

```text
Write Python NumPy code to reverse the array created in the previous question so that the first element becomes the last. Print the reversed array.
```

---

## Question 3

**Task:** Create a 3x3 matrix with values ranging from `0` to `8`.

```text
Write Python NumPy code to create a 3x3 matrix containing values from 0 to 8. Use np.arange and reshape. Print the matrix.
```

---

## Question 4

**Task:** Find indices of non-zero elements from `[1, 2, 0, 0, 4, 0]`.

```text
Write Python NumPy code to find the indices of non-zero elements in the array [1, 2, 0, 0, 4, 0]. Print only the indices.
```

---

## Question 5

**Task:** Create a 3x3x3 array with random values.

```text
Write Python NumPy code to create a 3x3x3 array filled with random values between 0 and 1. Print the array and its shape.
```

---

## Question 6

**Task:** Create a 10x10 array with random values and find the minimum and maximum values.

```text
Write Python NumPy code to create a 10x10 array of random values. Find and print the minimum and maximum values in the array.
```

---

## Question 7

**Task:** Create a random vector of size 30 and find the mean value.

```text
Write Python NumPy code to create a random vector of size 30. Calculate and print the mean value of the vector.
```

---

## Question 8

**Task:** Create a 2D array with `1` on the border and `0` inside.

```text
Write Python NumPy code to create a 5x5 2D array with 1 on the border and 0 inside. Print the final array.
```

---

## Question 9

**Task:** Multiply a 5x3 matrix by a 3x2 matrix using real matrix multiplication.

```text
Write Python NumPy code to create a random 5x3 matrix and a random 3x2 matrix. Multiply them using real matrix multiplication with np.dot, then print both matrices and the result.
```

---

## Question 10

**Task:** Extract the integer part of a random array.

```text
Write Python NumPy code to create a 3x3 random array with decimal values from 0 to 10. Extract the integer part using astype(int), and print only the integer-part array.
```

---

## Question 11

**Task:** Create a 5x5 matrix with row values ranging from `0` to `4`.

```text
Write Python NumPy code to create a 5x5 matrix where each row contains the values 0, 1, 2, 3, 4. Print the matrix.
```

---

## Question 12

**Task:** Create a random vector of size 10 and sort it.

```text
Write Python NumPy code to create a random vector of size 10. Sort it in ascending order and print the sorted vector.
```

---

## Question 13

**Task:** Consider two random arrays `A` and `B`, and check if they are equal.

```text
Write Python NumPy code to create two random arrays A and B. Check whether they are exactly equal using np.array_equal. Print A, B, and the result.
```

---

## Question 14

**Task:** Tell if a given 2D array has null columns.

```text
Write Python NumPy code to check whether a given 2D array has any null columns, where a null column means all values in that column are 0. Print the indices of null columns and whether any null columns exist.
```

---

## Question 15

**Task:** For a four-dimensional array, get the sum over the last two axes at once.

```text
Write Python NumPy code to create a random integer 4D array with shape (2, 3, 4, 5). Then get the sum over the last two axes by applying sum over axis=3 and then axis=2. Print the final result.
```

**Alternative shorter prompt:**

```text
Write Python NumPy code to create a random integer 4D array with shape (2, 3, 4, 5). Sum over the last two axes at once using axis=(2, 3), and print the resulting 2D array.
```

---

## Question 16

**Task:** Multiply an array of dimension `(5, 5, 3)` by an array with dimensions `(5, 5)`.

```text
Write Python NumPy code to create array A with shape (5, 5, 3) and array B with shape (5, 5). Multiply A by B using broadcasting by expanding B with B[:, :, np.newaxis]. Print the shape of the result.
```

---

## Question 17

**Task:** Extract all contiguous 3x3 blocks from a random 10x10 matrix.

```text
Write Python NumPy code to create a random 10x10 integer matrix using np.random.randint. Print the original matrix. Then use nested for loops to extract and print every contiguous 3x3 submatrix, showing the row and column position of each submatrix.
```

---

## Question 18

**Task:** For a 16x16 array, get the block-sum with block size 4x4.

```text
Write Python NumPy code to create a 16x16 array using np.arange(16 * 16).reshape(16, 16). Print the original array. Then calculate the sum of each non-overlapping 4x4 block using nested for loops, store the sums in a list, convert the list to a NumPy array, reshape it to 4x4, and print the block-sum matrix.